server:
    port: 12000

management:
  security:
    enabled: false

spring:
  main:
    banner-mode: 'off'
  application:
    name: test

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
# spring.datasource.schema: classpath:/schema.sql
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

hello:
  world:
   message: This is a message configured from the application.yml.

test:
  service:
    url: https://jsonplaceholder.typicode.com/posts/1